# File: Dockerfile.web
# Description: Web SPA image (T6.5)
# Author: Sri Yanto Qodarbaskoro
# Contact: sqodarbaskoro@gmail.com
# LinkedIn: https://www.linkedin.com/in/sqodarbaskoro/
# Website: https://www.seismopilot.com
# Created: 2026-09-16
# Modified: 2026-09-16
# Version: 0.1.0
# Copyright: © 2026 Sri Yanto Qodarbaskoro
FROM node:22.19.0-alpine@sha256:d2166de198f26e17e5a442f537754dd616ab069c47cc57b889310a717e0abbf9
WORKDIR /app
COPY apps/web /app
CMD ["npm", "run", "preview"]
